server:
  port: 8080
  # 激活环境
spring:
  profiles:
    active: @spring.profiles.active@
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 10

  main:
    allow-bean-definition-overriding:
      true
    # 映射文件位置
mybatis:
  mapper-locations: classpath:mapper/**/*.xml

# 如果只是* 需要"*"
com:
  briup:
    config:
      cors:
        pathPattern: /**
        origins:
          - "*"
        methods:
          - "GET"
          - "POST"
          - "PUT"
          - "OPTIONS"
          - "DELETE"
          - "PATCH"
        headers:
          - "*"
        allowCredentials: false
        maxAge: 3600
      swagger:
        enabled: true
        title: 中台管理系统
        description: vanse开发
        authAnts:
          - /config/**
          - /user/**
      logging:
        enabled: false
      jwt:
        authPaths:
          - /config/**
          - /user/**



fdfs:
  # 连接超时时间
  connect-timeout: 600
  # 读取时间
  so-timeout: 1500
  tracker-list:
    - 192.168.23.133:22122
  # 缩略图配置
  thumb-image:
    width: 100
    height: 100


